/**
 * Plan Models for PlannerExecutorAgent
 *
 * Zod schemas and types for execution plans, steps, and verification predicates.
 * Ported from Python SDK's Pydantic models.
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Predicate Specification
// ---------------------------------------------------------------------------

/**
 * Schema for verification predicate specification.
 *
 * Predicates are used to verify step outcomes:
 * - url_contains: Check if URL contains a substring
 * - url_matches: Check if URL matches a pattern
 * - exists: Check if element exists
 * - not_exists: Check if element does not exist
 * - element_count: Check element count within range
 * - any_of: Any predicate passes
 * - all_of: All predicates pass
 */
export const PredicateSpecSchema = z.object({
  predicate: z
    .string()
    .describe('Predicate type: url_contains, exists, not_exists, any_of, all_of, element_count'),
  args: z.array(z.any()).default([]).describe('Predicate arguments'),
});

export type PredicateSpec = z.infer<typeof PredicateSpecSchema>;

// ---------------------------------------------------------------------------
// Plan Step
// ---------------------------------------------------------------------------

/**
 * Action types supported by the executor.
 */
export const ActionType = z.enum([
  'NAVIGATE',
  'CLICK',
  'TYPE',
  'TYPE_AND_SUBMIT',
  'SCROLL',
  'PRESS',
  'WAIT',
  'EXTRACT',
  'DONE',
]);

export type ActionType = z.infer<typeof ActionType>;

/**
 * Type for a plan step.
 */
export interface PlanStep {
  id: number;
  goal: string;
  action: string;
  target?: string;
  intent?: string;
  input?: string;
  verify: PredicateSpec[];
  required: boolean;
  stopIfTrue: boolean;
  optionalSubsteps: PlanStep[];
  heuristicHints: Record<string, unknown>[];
}

/**
 * Schema for a single step in the execution plan.
 * Note: For simplicity, optionalSubsteps validation is shallow (z.any()).
 * Full recursive validation happens at runtime if needed.
 */
export const PlanStepSchema = z.object({
  id: z.number().describe('Step ID (1-indexed, contiguous)'),
  goal: z.string().describe('Human-readable goal for this step'),
  action: z
    .string()
    .describe('Action type: NAVIGATE, CLICK, TYPE_AND_SUBMIT, SCROLL, EXTRACT, DONE'),
  target: z.string().optional().describe('URL for NAVIGATE action'),
  intent: z.string().optional().describe('Intent hint for CLICK action'),
  input: z.string().optional().describe('Text for TYPE_AND_SUBMIT action'),
  verify: z.array(PredicateSpecSchema).default([]).describe('Verification predicates'),
  required: z.boolean().default(true).describe('If True, step failure triggers replan'),
  stopIfTrue: z
    .boolean()
    .default(false)
    .describe('If True, stop execution when verification passes'),
  optionalSubsteps: z.array(z.any()).default([]).describe('Optional fallback steps'),
  heuristicHints: z
    .array(z.record(z.any()))
    .default([])
    .describe('Planner-generated hints for element selection'),
});

// ---------------------------------------------------------------------------
// Plan
// ---------------------------------------------------------------------------

/**
 * Schema for execution plan generated by the Planner.
 */
export const PlanSchema = z.object({
  task: z.string().describe('Original task description'),
  notes: z.array(z.string()).default([]).describe('Planner notes/assumptions'),
  steps: z.array(PlanStepSchema).describe('Ordered execution steps'),
});

export type Plan = z.infer<typeof PlanSchema>;

// ---------------------------------------------------------------------------
// Replan Patch
// ---------------------------------------------------------------------------

/**
 * Schema for plan patch (used when replanning after step failure).
 */
export const ReplanPatchSchema = z.object({
  mode: z.literal('patch'),
  replaceSteps: z
    .array(
      z.object({
        id: z.number(),
        step: PlanStepSchema,
      })
    )
    .describe('Steps to replace by ID'),
});

export type ReplanPatch = z.infer<typeof ReplanPatchSchema>;

// ---------------------------------------------------------------------------
// Action Record (for stepwise planning history)
// ---------------------------------------------------------------------------

/**
 * Record of an executed action for history tracking in stepwise planning.
 */
export interface ActionRecord {
  /** Step number (1-indexed) */
  stepNum: number;
  /** Action type (CLICK, TYPE_AND_SUBMIT, SCROLL, etc.) */
  action: string;
  /** Element description or URL */
  target: string | null;
  /** Outcome (success, failed) */
  result: string;
  /** URL after action completed */
  urlAfter: string | null;
}

// ---------------------------------------------------------------------------
// Step Outcome
// ---------------------------------------------------------------------------

/**
 * Status of a step execution.
 */
export enum StepStatus {
  SUCCESS = 'success',
  FAILED = 'failed',
  SKIPPED = 'skipped',
  VISION_FALLBACK = 'vision_fallback',
}

/**
 * Result of executing a single plan step.
 */
export interface StepOutcome {
  stepId: number;
  goal: string;
  status: StepStatus;
  actionTaken?: string;
  verificationPassed: boolean;
  usedVision: boolean;
  error?: string;
  durationMs: number;
  urlBefore?: string;
  urlAfter?: string;
  extractedData?: unknown;
}

// ---------------------------------------------------------------------------
// Run Outcome
// ---------------------------------------------------------------------------

/**
 * Result of a complete agent run.
 */
export interface RunOutcome {
  runId: string;
  task: string;
  success: boolean;
  stepsCompleted: number;
  stepsTotal: number;
  replansUsed: number;
  stepOutcomes: StepOutcome[];
  totalDurationMs: number;
  error?: string;
  tokenUsage?: TokenUsageSummary;
  fallbackUsed: boolean;
}

// ---------------------------------------------------------------------------
// Token Usage Tracking
// ---------------------------------------------------------------------------

/**
 * Token usage totals for a single role or model.
 */
export interface TokenUsageTotals {
  calls: number;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

/**
 * Summary of all token usage.
 */
export interface TokenUsageSummary {
  total: TokenUsageTotals;
  byRole: Record<string, TokenUsageTotals>;
  byModel: Record<string, TokenUsageTotals>;
}

// ---------------------------------------------------------------------------
// Snapshot Types
// ---------------------------------------------------------------------------

/**
 * Snapshot element for context formatting.
 */
export interface SnapshotElement {
  id: number;
  role?: string;
  text?: string;
  name?: string;
  importance?: number;
  isPrimary?: boolean;
  background?: boolean;
  clickable?: boolean;
  nearbyText?: string;
  ordinal?: string;
  inDominantGroup?: boolean;
  href?: string;
  ariaLabel?: string;
}

/**
 * Snapshot data from browser runtime.
 */
export interface Snapshot {
  url: string;
  title: string;
  elements: SnapshotElement[];
  screenshot?: string;
  status?: string;
}

// ---------------------------------------------------------------------------
// Snapshot Context
// ---------------------------------------------------------------------------

/**
 * Shared page state between Planner and Executor.
 *
 * Enables snapshot sharing to avoid redundant captures and
 * tracks metadata for vision fallback decisions.
 */
export interface SnapshotContext {
  /** The snapshot data */
  snapshot: Snapshot | null;
  /** Compact representation for LLM context */
  compactRepresentation: string;
  /** Base64-encoded screenshot */
  screenshotBase64: string | null;
  /** When the snapshot was captured */
  capturedAt: Date;
  /** Element limit used for this snapshot */
  limitUsed: number;
  /** Whether snapshot was successful */
  snapshotSuccess: boolean;
  /** Whether vision fallback is required */
  requiresVision: boolean;
  /** Reason for vision fallback */
  visionReason: string | null;
  /** Pruning category used (if any) */
  pruningCategory: string | null;
  /** Number of elements after pruning */
  prunedNodeCount: number;
}

// ---------------------------------------------------------------------------
// Parsed Action
// ---------------------------------------------------------------------------

/**
 * Parsed action from executor response.
 */
export interface ParsedAction {
  action: string;
  args: unknown[];
}
